### ISSUE TITLE
Please make this for the Linux SDK too

### ISSUE THREAD

**Issue by mxa** [kenhys/debian-leapmotion#1]
Great way to get the Leap motion Linux driver going on Linux. Is it possible to have a version for the SDK as well? Possibly even for the "Hotfix" version that reportedly solved a crasher bug for some users. It's available here https://community.leapmotion.com/t/error-in-leapd-malloc/4271/6 (see post of jdonald)

**Comment by kenhys** [comment]
Hi, @mxa.

Thank you for feedback.

I've fixed Makefile to support it, but not tested yet.
Could you try it master version again?

P.S. Is the "Hotfix" still unofficial one? If so, it seems that it is better to encourage leap motion team to make it as official.

**Comment by kenhys** [comment]
In this issue,  the "Hotfix" will not be supported because I don't know the "Hotfix" well.

It should be, I'll try to patch it later.

**Comment by kenhys** [comment]
Could you reopen, if the fix doesn't work correctly.

**Comment by mxa** [comment]
Hi @kenhys 
>  Is the "Hotfix" still unofficial one? If so, it seems that it is better to encourage leap motion team to make it as official.

Unfortunately, it seems that there will be no more work done by Leap Motion for the Linux platform and this hotfix version from November 2015 is the newest thing out there, and might be the last one. It fixes a bug, but "It's built off a development branch and hasn't gone through our standard QA". Quoting @LeapMotion: "Our core focus is VR, i.e. Windows + Android. Until VR headsets support Mac/Linux, we're not able to dedicate eng resources there"
