### ISSUE TITLE
Leap motion process error appear after using apt command

### ISSUE THREAD

**Issue by dwisatriow** [kenhys/debian-leapmotion#2]
Hi, i just installed debian-leapmotion and after i installed it, i got error message as follow

> Setting up leap (2.3.1+31549-0.1) ...
Enable Leap Motion by default
Synchronizing state of leapd.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable leapd
update-rc.d: error: cannot find a LSB script for leapd
dpkg: error processing package leap (--configure):
 installed leap package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 leap
E: Sub-process /usr/bin/dpkg returned an error code (1)

When i tried to use the leap motion with processing it looks works well.
The problem is, when i used apt command like for installing package the error message above keep appearing following the installation output. Any idea to fix this? Please help to solve it.

**Comment by kenhys** [comment]
@dwisatriow 

This repository is targetted to debian/unstable.
And it seems that I can't reproduce it on current debian/unstable.
If you use other debian flavors, it may fail.

```
 LANG=C sudo dpkg -i ./Leap-2.3.1+31549-0.1-x64.deb
Selecting previously unselected package leap.
(Reading database ... 471228 files and directories currently installed.)
Preparing to unpack ./Leap-2.3.1+31549-0.1-x64.deb ...
Unpacking leap (2.3.1+31549-0.1) ...
Setting up leap (2.3.1+31549-0.1) ...
Enable Leap Motion by default
Created symlink /etc/systemd/system/multi-user.target.wants/leapd.service -> /lib/systemd/system/leapd.service.
Open the Leap Motion GUI with:
  LeapControlPanel
See /usr/share/Leap/README.linux for more information.
LANG=C sudo dpkg -i ./Leap-2.3.1+31549-0.1-x64.deb  6.12s user 0.87s system 105% cpu 6.608 total
```

**Comment by dwisatriow** [comment]
@kenhys I'm using debian buster (current testing). I think the problem starts when i installed leapmotion (for ubuntu) then uninstalling it and installing debian-leapmotion. Is it because the uninstall process doesn't works completely?

**Comment by kenhys** [comment]
@dwisatriow 

To clarify the issue, did you mean the following steps on buster?

$buster> sudo dpkg -i Leap-2.3.1+31549-x64.deb (offical deb package)
$buster> sudo apt purge leap (uninstall official deb package)
$buster> sudo dpkg -i Leap-2.3.1+31549-0.1-x64.deb

**Comment by dwisatriow** [comment]
@kenhys Yes, btw i uninstalled official deb package from synaptic by choosing completely remove option, since i don't really know to how do it in command line.

**Comment by kenhys** [comment]
@dwisatriow 

The problem is caused by empty `/etc/init.d/leapd`. 
It seems that `sudo dpkg -i Leap-2.3.1+31549-x64.deb` creates it.
So, you should remove it manually.

```
ls -la /etc/init.d/leapd 
-rw-r--r-- 1 root root 0  2月 26 23:23 /etc/init.d/leapd
```

```
$ LANG=C dpkg -S /etc/init.d/leapd 
dpkg-query: no path found matching pattern /etc/init.d/leapd
```

**Comment by dwisatriow** [comment]
@kenhys The installation has worked well, just after deleting `/etc/init.d/leapd`.
Thanks for your time and help.

**Comment by kenhys** [comment]
I'm happy to hear that!
