### ISSUE TITLE
dependency error on raspbian stretch 14.x

### ISSUE THREAD

**Issue by Karthickvhora** [kenhys/debian-leapmotion#3]
Hi , 
     Can you help me figure this out?
dpkg: error processing package leap:amd64 (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of leap:amd64:
 leap:amd64 depends on libc6 (>= 2.15-0).
 leap:amd64 depends on libgl1-mesa-glx (>= 7.7.1) | libgl1-mesa-glx-lts-precise (>= 7.7.1) | libgl1-mesa-glx-lts-quantal (>= 7.7.1) | libgl1-mesa-glx-lts-raring (>= 7.7.1) | libgl1-mesa-glx-lts-saucy (>= 7.7.1) | libgl1-mesa-glx-lts-trusty (>= 7.7.1) | libgl1-mesa-glx-lts-utopic (>= 7.7.1) | libgl1-mesa-glx-lts-vivid (>= 7.7.1).
 leap:amd64 depends on libglu1-mesa (>= 7.7.1).
 leap:amd64 depends on libxi6 (>= 2:1.3-3).
 leap:amd64 depends on libxxf86vm1 (>= 1:1.1.0-2).
 leap:amd64 depends on libdbus-1-3 (>= 1.0.2).

and by the way, I tried patching x86bit leap file, changing the file name in the make file, but it didnt work. 
Note : OS is raspbian stretch 14.x

**Comment by kenhys** [comment]
@Karthickvhora 
This repository is targetted debian/unstable, so there is no surprise that it didn't suite for you.

Anyway, I don't have raspbian, so only I could say: it is better to check  whether all `depends on XXX` packages (libc6, libgl1-mesa-glx... and so on) are installed.
